FROM provisioning_maven

MAINTAINER Tim Perry

WORKDIR /opt
RUN sudo apt-get update -y
#RUN mysql_secure_installation
#RUN mysql_install_db
RUN sudo wget http://dev.mysql.com/get/mysql-apt-config_0.6.0-1_all.deb
#RUN echo "3" | dpkg -i mysql-apt-config_0.6.0-1_all.deb
#ENTRYPOINT mysql --version && bash
